name: Deploy Histoire

on:
  push:
    branches:
      - master

env:
  HISTOIRE_BASE: /histoire-ghpages-repro/

jobs:
  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Restore Lerna Cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install node_modules
        run: npm install

      - uses: actions/cache@v2
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: Build
        run: npm run story:build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: ./.histoire/dist
